name: Create and run URL finder script
  run: |
    echo "Searching for URLs in files..."
    > found_urls.txt
    find . -type f ! -path "./.git/*" ! -path "./node_modules/*" ! -name '*.png' ! -name '*.jpg' ! -name '*.jpeg' ! -name '*.gif' ! -name '*.ico' | while read -r file; do
      if file "$file" | grep -q text; then
        grep -Eoi 'http[s]?://[^"'\'' )>\]]+|www\.[^"'\'' )>\]]+' "$file" >> found_urls.txt || true
      fi
    done
    sort -u found_urls.txt -o found_urls.txt
    echo "✅ Found URLs:"
    cat found_urls.txt || echo "No URLs found."
